name: logo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.6
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1
  uuid: ^4.1.0
  flutter_secure_storage: ^9.0.0
  carousel_slider: ^4.2.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/images/splash.png
#   android: true
#   ios: false
#   fullscreen: true
#   android_gravity: fill
#   ios_content_mode: scaleToFill

flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true
